version: 0.2

phases:
  install:
    runtime-versions:
      java: openjdk8
    commands:
      - echo "Scanning for security vulnerability within dependencies"
      
  pre_build:
    commands:
      - echo "validating project"
      - mvn validate
  build:
    commands:
      - echo "Building project using maven"
      - mvn clean install -Dmaven.test.skip=true
       
  post_build:
    commands:
      - echo Build completed on `date`
      - mvn package
artifacts:
  files:
    - webapp/target/*.war
    - server/target/*.jar
cache:
  paths:
    - '/root/.m2/**/*'
